language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

sudo: false

#matrix:
#  fast_finish: true
#  include:
#    - os: osx
#      language: generic
#      python:

install: "pip install --upgrade -r requirements/travis.txt"

script:
  - flake8 *.py
  - make tests

after_success:
  - coveralls
